CI-Build auto upload to Release in Pre-Release
FCL-Team/FoldCraftLauncher pull request #315
Opened 2024-03-21 04:28 UTC by 8MiYile

2024-03-21 07:12 UTC, zkitefly requested changes

2024-03-21 07:12 UTC, zkitefly commented on .github/workflows/main.yml
> +    runs-on: ubuntu-20.04
不推荐指定版本号，建议使用 `ubuntu-latest`

2024-03-21 07:13 UTC, zkitefly commented on .github/workflows/main.yml
> +    runs-on: ubuntu-20.04
emm，好吧，怎么原来就指定的（

没事了（

2024-03-26 15:05 UTC, Deep-Dark-Forest commented
@FCL-Team别装死啊（

2024-03-26 16:00 UTC, kjjjjjjjjjjjj commented
So nice

2024-08-06 16:20 UTC, closed without merging